baseURL: "https://natel.at.eu.org"
#theme: "up-business-theme"
languageCode: "en-us"

title: "Natel"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Natel"
  description: "Nos especializamos en diseñar y llevar adelante proyectos técnicos presentados ante la Conatel, Paraguay."
  images:
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Asunción, Paraguay"
    - "Estrella y Oleary"

  contact:
    - "natel@natel.site"
    - "+595 984 444 776"

  copyright: "© 2024 Natel"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Nuestro trabajo"
      url: "/nuestro-trabajo"
      weight: 2

    - name: "Producción"
      url: "/proyectos-tecnicos-produccion"
      weight: 3

    - name: "Presupuesto"
      url: "/presupuesto"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Contacte"
      url: "/contacto"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Nuestro trabajo"
      url: "/nuestro-trabajo"
      weight: 2

    - name: "Nosotros"
      url: "/nosotros"
      weight: 3

    - name: "Presupuesto"
      url: "/presupuesto"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
